<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_60548a8e93475',
    'title' => 'Url de services',
    'fields' => array(
        array(
            'key' => 'field_6056902922fe1',
            'label' => '',
            'name' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_6054923222fe2',
                    'label' => 'Type de produit',
                    'name' => 'intranet_type_de_produit',
                    'type' => 'text',
                    'instructions' => 'Ex : calendarbasedproduct, filetree',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6055a04c22fe3',
                    'label' => 'URL du service',
                    'name' => 'intranet_url_du_service',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_60b7905222fe4',
                    'label' => 'URL du package',
                    'name' => 'intranet_url_du_package',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'sedoo-intranet-services-admin-page',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));


acf_add_local_field_group(array(
    'key' => 'group_6231ff4e5fc5e',
    'title' => 'Contacts / Fichiers en relation',
    'fields' => array(
        array(
            'key' => 'field_6231ff65ef70f',
            'label' => 'Contacts',
            'name' => 'intranet_taxo_contacts',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_6231ffa1ef30a',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_62320092ef30c',
                    'label' => 'Nom du service proposé',
                    'name' => 'intranet_taxo_contact_service_name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6231ffa1ef30a',
                    'label' => 'Adresse générique du service',
                    'name' => 'intranet_taxo_contact_service_mail',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6231ffe1ef30b',
                    'label' => 'Liste des gestionnaires',
                    'name' => 'intranet_taxo_contact_userlist',
                    'type' => 'user',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'role' => '',
                    'allow_null' => 0,
                    'multiple' => 1,
                    'return_format' => 'array',
                ),
            ),
        ),
        array(
            'key' => 'field_6232038f994b5',
            'label' => 'Racine de l\'arborescence de fichiers',
            'name' => 'intranet_taxo_root',
            'type' => 'text',
            'instructions' => 'Récupérer la fin de l\'url manquante pour accéder au dossier, depuis le gestionnaire de fichiers <a href="https://fb2.sedoo.fr/" target="_blank">"fileBrowser" </a>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'irap/Finances/Achats/',
            'prepend' => 'https://fb2.sedoo.fr/files/',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'category',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

endif;		

?>