<?php
if( function_exists('acf_add_local_field_group') ):

// SERVICE REST SEDOO
acf_add_local_field_group(array(
	'key' => 'group_623ddc96cf354',
	'title' => 'REST API SEDOO',
	'fields' => array(
		array(
			'key' => 'field_623ddcc2c273f',
			'label' => 'Adresse du getfile',
			'name' => 'intranet_API_getfile_url',
			'type' => 'text',
			'instructions' => 'https://api.sedoo.fr/intranet-omp-service-rest/data/v1_0/getfile?product=intranet-filetree&campaign=intranetomp&file=',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'https://api.sedoo.fr/intranet-omp-service-rest/data/v1_0/getfile?product=intranet-filetree&campaign=intranetomp&file=',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'sedoo-intranet-services-admin-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

// Dossiers filebrowser  -- contact en commentaire pour l'instant
acf_add_local_field_group(array(
    'key' => 'group_6231ff4e5fc5e',
    'title' => 'Fichiers en relation',
    'fields' => array(
        // array(
        //     'key' => 'field_6231ff65ef70f',
        //     'label' => 'Contacts',
        //     'name' => 'intranet_taxo_contacts',
        //     'type' => 'repeater',
        //     'instructions' => '',
        //     'required' => 0,
        //     'conditional_logic' => 0,
        //     'wrapper' => array(
        //         'width' => '',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'collapsed' => 'field_6231ffa1ef30a',
        //     'min' => 0,
        //     'max' => 0,
        //     'layout' => 'table',
        //     'button_label' => '',
        //     'sub_fields' => array(
        //         array(
        //             'key' => 'field_62320092ef30c',
        //             'label' => 'Nom du service proposé',
        //             'name' => 'intranet_taxo_contact_service_name',
        //             'type' => 'text',
        //             'instructions' => '',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'default_value' => '',
        //             'placeholder' => '',
        //             'prepend' => '',
        //             'append' => '',
        //             'maxlength' => '',
        //         ),
        //         array(
        //             'key' => 'field_6231ffa1ef30a',
        //             'label' => 'Adresse générique du service',
        //             'name' => 'intranet_taxo_contact_service_mail',
        //             'type' => 'email',
        //             'instructions' => '',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'default_value' => '',
        //             'placeholder' => '',
        //             'prepend' => '',
        //             'append' => '',
        //         ),
        //         array(
        //             'key' => 'field_6231ffe1ef30b',
        //             'label' => 'Liste des gestionnaires',
        //             'name' => 'intranet_taxo_contact_userlist',
        //             'type' => 'user',
        //             'instructions' => '',
        //             'required' => 0,
        //             'conditional_logic' => 0,
        //             'wrapper' => array(
        //                 'width' => '',
        //                 'class' => '',
        //                 'id' => '',
        //             ),
        //             'role' => '',
        //             'allow_null' => 0,
        //             'multiple' => 1,
        //             'return_format' => 'array',
        //         ),
        //     ),
        // ),
        array(
            'key' => 'field_6232038f994b5',
            'label' => 'Racine de l\'arborescence de fichiers',
            'name' => 'intranet_taxo_root',
            'type' => 'text',
            'instructions' => 'Récupérer la fin de l\'url manquante pour accéder au dossier, depuis le gestionnaire de fichiers <a href="https://fb2.sedoo.fr/" target="_blank">"fileBrowser" </a>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'irap/Finances/Achats/',
            'prepend' => 'https://fb2.sedoo.fr/files/',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'category',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

//fichiers en relation sur filebrowser
acf_add_local_field_group(array(
	'key' => 'group_623b3e7e0a9c3',
	'title' => 'Ajout de ressources en relation',
	'fields' => array(
		array(
			'key' => 'field_623b3e8a0aa3a',
			'label' => 'Fichiers/liens',
			'name' => 'intranet_relatedfile',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_623b3f460aa3c',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Ajouter un fichier/lien',
			'sub_fields' => array(
				array(
					'key' => 'field_623b3f460aa3c',
					'label' => 'Nom explicite',
					'name' => 'intranet_relatedfile_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_623dde4c5e696',
					'label' => 'Source',
					'name' => 'intranet_relatedfile_source',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'interne' => 'Interne: Fichier déposé sur filebrowser',
						'interneForm' => 'Interne: formulaires en ligne',
						'externe' => 'Externe (page intranet tutelle, autres)',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'array',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_623b3ec00aa3b',
					'label' => 'URL du fichier interne',
					'name' => 'intranet_relatedfile_internal_url',
					'type' => 'text',
					'instructions' => 'Récupérer la fin de l\'url manquante pour accéder au dossier, depuis le gestionnaire de fichiers <a href="https://fb2.sedoo.fr/" target="_blank">"fileBrowser" </a>',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_623dde4c5e696',
								'operator' => '==',
								'value' => 'interne',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'irap/Finances/Achats/nom_du_fichier.extension',
					'prepend' => 'https://fb2.sedoo.fr/files/',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62456e056cc49',
					'label' => 'Page de formulaire en relation',
					'name' => 'intranet_relatedfile_internal_url_form',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_623dde4c5e696',
								'operator' => '==',
								'value' => 'interneForm',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'page',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
						1 => 'taxonomy',
					),
					'elements' => '',
					'min' => '',
					'max' => '1',
					'return_format' => 'object',
				),
				array(
					'key' => 'field_623ddf213b2ee',
					'label' => 'URL du fichier externe',
					'name' => 'intranet_relatedfile_external_url',
					'type' => 'text',
					'instructions' => 'Récupérer l\'url complète de la page où est hébergé le fichier',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_623dde4c5e696',
								'operator' => '==',
								'value' => 'externe',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

// Déclarer un service
acf_add_local_field_group(array(
	'key' => 'group_62330e13209bb',
	'title' => 'Déclarer un service',
	'fields' => array(
		array(
			'key' => 'field_62330e2ae2563',
			'label' => 'Description du service',
			'name' => 'intranet_service',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_62330e7ce2564',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Ajouter un service',
			'sub_fields' => array(
				array(
					'key' => 'field_62330eb4e2566',
					'label' => 'Catégorie',
					'name' => 'intranet_service_categorie',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'add_term' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'object',
					'multiple' => 0,
				),
				array(
					'key' => 'field_62330e7ce2564',
					'label' => 'nom du service',
					'name' => 'intranet_service_nom',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62330e9ee2565',
					'label' => 'Mail de contact',
					'name' => 'intranet_service_mail',
					'type' => 'email',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_623b02e25e797',
					'label' => 'Gestionnaire(s) en charge',
					'name' => 'intranet_service_gestionnaires',
					'type' => 'user',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 0,
					'multiple' => 1,
					'return_format' => 'object',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-gestion-des-services',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));
	
// Applications externes
acf_add_local_field_group(array(
	'key' => 'group_62332d0123e8c',
	'title' => 'Ajouter une application',
	'fields' => array(
		array(
			'key' => 'field_62332d013232a',
			'label' => 'Application en ligne externe',
			'name' => 'intranet_apiext',
			'type' => 'repeater',
			'instructions' => 'Pour les icônes, voir https://fonts.google.com/icons?icon.query=car&icon.style=Filled<br>Insérer le nom de l\'icône (voir fenetre droite après selection de l\'icône',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_62332d0133ab5',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Ajouter un service externe',
			'sub_fields' => array(
				array(
					'key' => 'field_62332d0133ab5',
					'label' => 'nom de l\'application',
					'name' => 'intranet_apiext_application_nom',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62332a2633ab5',
					'label' => 'Description',
					'name' => 'intranet_apiext_application_description',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62332d0133abf',
					'label' => 'URL du service',
					'name' => 'intranet_apiext_application_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_62332d0133adb',
					'label' => 'Catégorie',
					'name' => 'intranet_apiext_application_categorie',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'add_term' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'object',
					'multiple' => 0,
				),
				array(
					'key' => 'field_62332eb41c13d',
					'label' => 'Icône',
					'name' => 'intranet_apiext_application_icone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'identifiant de l\'icône ',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-applications-externes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));
    
/**
 * BLOCKS
 */
// Filetree
acf_add_local_field_group(array(
	'key' => 'group_6244220d40ea0',
	'title' => 'Block filetree',
	'fields' => array(
		array(
			'key' => 'field_624426d2b7342',
			'label' => 'Titre du bloc',
			'name' => 'intranet_filetree_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Tous les fichiers de la catégorie XXXX',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_624426efb7343',
			'label' => 'Description',
			'name' => 'intranet_apiext_block_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_62442768b7344',
			'label' => 'Associer à une catégorie ?',
			'name' => 'intranet_filetree_block_association',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_624425ecb7341',
			'label' => 'Racine de l\'arborescence de fichiers',
			'name' => 'intranet_filetree_block_root',
			'type' => 'text',
			'instructions' => 'Récupérer la fin de l\\\'url manquante pour accéder au dossier, depuis le gestionnaire de fichiers <a href="https://fb2.sedoo.fr/" target="_blank">"fileBrowser" </a>',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_62442768b7344',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'LABO/finances/achats/',
			'prepend' => 'https://fb2.sedoo.fr/files/',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_624427afb7345',
			'label' => 'Catégorie à associer',
			'name' => 'intranet_filetree_block_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_62442768b7344',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/intranet-filetree-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

// liste services extérieur
acf_add_local_field_group(array(
	'key' => 'group_6241d783272d1',
	'title' => 'Block apiext',
	'fields' => array(
		array(
			'key' => 'field_6241d79ea8e46',
			'label' => 'Titre',
			'name' => 'intranet_apiext_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6241d7b8a8e47',
			'label' => 'Catégorie',
			'name' => 'intranet_apiext_block_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_6241d8622a428',
			'label' => 'Description',
			'name' => 'intranet_apiext_block_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/intranet-apiext-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

// Tile Block Accueil intranet
acf_add_local_field_group(array(
	'key' => 'group_62629ed56c157',
	'title' => 'intranet tile field',
	'fields' => array(
		array(
			'key' => 'field_62629f2f9d71c',
			'label' => 'titre',
			'name' => 'intranet_tile_block_title',
			'type' => 'text',
			'instructions' => 'Saisissez le titre de votre tuile',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Saisir le titre ici',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62629f9a9d71d',
			'label' => 'Description',
			'name' => 'intranet_tile_block_description',
			'type' => 'text',
			'instructions' => 'Donner une brève description à votre tuile',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Saisir la description ici',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6262a0009d71e',
			'label' => 'Lien externe ou interne',
			'name' => 'intranet_tile_block_link_choice',
			'type' => 'radio',
			'instructions' => 'Merci d\'indiquer s\'il s\'agit d\'une tuile redirigeant les utilisateurs vers un autre site internet ou application, ou bien si la tuile redirige vers une page de l\'intranet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'externe' => 'Lien externe',
				'interne' => 'Lien Interne',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'Lien externe',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6262a08c9d71f',
			'label' => 'Lien externe',
			'name' => 'intranet_tile_block_external_link',
			'type' => 'url',
			'instructions' => 'Saisissez l\'url du site ou de l\'application vers qui vous souhaitez rediriger l\'utilisateur',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6262a0009d71e',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_6262a1d29d720',
			'label' => 'Lien Interne',
			'name' => 'intranet_tile_block_internal_link',
			'type' => 'page_link',
			'instructions' => 'Choisissez la page vers qui vous souhaitez rediriger l\'utilisateur',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6262a0009d71e',
						'operator' => '==',
						'value' => 'interne',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array(
			'key' => 'field_6262a25b9d721',
			'label' => 'Couleur de fond',
			'name' => 'intranet_tile_block_bg_color',
			'type' => 'color_picker',
			'instructions' => 'Choisissez une couleur de fond à votre tuile',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 1,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6262a2f79d722',
			'label' => 'Couleur du texte',
			'name' => 'intranet_tile_block_text_color',
			'type' => 'color_picker',
			'instructions' => 'Choisissez la couleur du texte de votre tuile',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
			'enable_opacity' => 0,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_6262a33d9d723',
			'label' => 'Icone',
			'name' => 'intranet_tile_block_icone',
			'type' => 'text',
			'instructions' => 'Saisissez ici le nom de l’Icône à intégrer - Choisissez parmi les icônes disponible sur la page suivante : https://fonts.google.com/icons',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'thumb_up',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6262a7c500e7c',
			'label' => 'Choix du bouton',
			'name' => 'intranet_tile_block_btn_choice',
			'type' => 'radio',
			'instructions' => 'Souhaitez-vous voir un bouton afficher dans votre tuile du type "En savoir plus" ? ( Vous pourrez modifier le texte par la suite)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'oui' => 'oui',
				'non' => 'non',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'oui',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6262a73700e7b',
			'label' => 'texte du bouton',
			'name' => 'intranet_tile_block_anchor_value',
			'type' => 'text',
			'instructions' => 'Saisissez le texte du bouton',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6262a7c500e7c',
						'operator' => '==',
						'value' => 'oui',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'En savoir plus',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/intranet-tile-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		

?>